seed: 2
model:
    arch: maple
    name: ViT-B/16
    prec: fp16
    n_ctx: 2
    ctx_init: a photo of a
    prompt_depth: 3
    pretrained_version: bioclip
    hierachical: true
    curv_version: learn2derive1
    curv_init: 0.05
    curv_i_init: 0.05
    curv_t_init: 0.025
    curv_m_init: 0.025
    max_epoch: 10
data:
    name: rarespecies
    loader: HierDataLoader
    data_root: prepro/raw/rarespecies
    train: prepro/data/rarespecies/gt_train.txt
    test: prepro/data/rarespecies/gt_test.txt
    hierarchy: prepro/data/rarespecies/tree.npy
    batch_size: 8
    test_batch_size: 1024
    n_workers: 4
    sampler:
        name: nshot
        nshot: 16
    transform: clip
init_label_set: leaf
optim:
    name: sgd
    lr: 0.03
    max_epoch: 10
    lr_scheduler: cosine
    warmup_epoch: 1
    warmup_type: constant
    warmup_cons_lr: 0.001
    use_scheduler: true
loss:
    name: ce
    lambda: 0.5
    mta_weight: 1
    align_weight: 0.5
    scaling_factor_i: 1.0
    scaling_factor_t: 1.0
print_freq: 20
exp: ViT-B_16/few_shot/16-shot/ours
treecut_generator:
    arch: treecut_generator
    dropout_rate: 0.1
